import uuid
from datetime import datetime
from sqlalchemy import Column, String, Text, Integer, Float, Boolean, DateTime, ForeignKey, Enum
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from app.db.session import Base
import enum


def generate_uuid():
    return str(uuid.uuid4())


class LearningPathStatus(str, enum.Enum):
    DRAFT = "draft"
    ACTIVE = "active"
    COMPLETED = "completed"
    PAUSED = "paused"


class LearningPath(Base):
    """
    A personalized learning path generated by AI Agent based on user's skill gap
    """
    __tablename__ = "learning_paths"
    
    id = Column(String(36), primary_key=True, default=generate_uuid)
    user_id = Column(String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Path metadata
    title = Column(String(300), nullable=False)
    description = Column(Text)
    target_skill = Column(String(200), nullable=False)  # e.g., "Leadership", "Negotiation"
    current_level = Column(String(50))  # beginner, intermediate, advanced
    target_level = Column(String(50))   # intermediate, advanced, expert
    
    # AI-generated content
    skill_gap_analysis = Column(Text)  # AI analysis of user's skill gap
    learning_objectives = Column(JSONB)  # ["Understand X", "Master Y", ...]
    estimated_hours = Column(Float)  # Total estimated learning time
    
    # Progress tracking
    status = Column(String(20), default=LearningPathStatus.ACTIVE.value)
    progress_percentage = Column(Float, default=0.0)
    completed_lessons = Column(Integer, default=0)
    total_lessons = Column(Integer, default=0)
    
    # Timestamps
    started_at = Column(DateTime)
    completed_at = Column(DateTime)
    last_activity_at = Column(DateTime)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    user = relationship("User", back_populates="learning_paths")
    lessons = relationship("LearningPathLesson", back_populates="learning_path", 
                          cascade="all, delete-orphan", order_by="LearningPathLesson.order")
    
    def __repr__(self):
        return f"<LearningPath {self.title}>"


class LearningPathLesson(Base):
    """
    A single lesson within a learning path, linked to a segment
    """
    __tablename__ = "learning_path_lessons"
    
    id = Column(String(36), primary_key=True, default=generate_uuid)
    learning_path_id = Column(String(36), ForeignKey("learning_paths.id", ondelete="CASCADE"), 
                              nullable=False, index=True)
    segment_id = Column(String(36), ForeignKey("segments.id", ondelete="SET NULL"), nullable=True)
    
    # Lesson details
    order = Column(Integer, nullable=False)  # Position in the path
    title = Column(String(300))  # Can override segment title
    description = Column(Text)  # Why this lesson is important
    learning_objective = Column(Text)  # What user will learn
    
    # AI-generated context
    context_notes = Column(Text)  # How this lesson connects to the path
    prerequisites = Column(JSONB)  # Lessons that should be completed first
    key_concepts = Column(JSONB)  # ["concept1", "concept2", ...]
    
    # Progress
    is_completed = Column(Boolean, default=False)
    is_locked = Column(Boolean, default=False)  # Locked until prerequisites done
    completed_at = Column(DateTime)
    watch_progress_seconds = Column(Integer, default=0)
    
    # Assessment (optional)
    quiz_questions = Column(JSONB)  # AI-generated quiz questions
    quiz_score = Column(Float)  # User's score on quiz
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    learning_path = relationship("LearningPath", back_populates="lessons")
    segment = relationship("Segment")
    
    def __repr__(self):
        return f"<LearningPathLesson {self.order}: {self.title}>"


class SkillAssessment(Base):
    """
    User's skill assessment used by AI to determine learning paths
    """
    __tablename__ = "skill_assessments"
    
    id = Column(String(36), primary_key=True, default=generate_uuid)
    user_id = Column(String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Assessment details
    skill_name = Column(String(200), nullable=False)
    category_id = Column(String(36), ForeignKey("categories.id", ondelete="SET NULL"))
    
    # Self-assessment
    current_level = Column(Integer)  # 1-5 scale
    target_level = Column(Integer)   # 1-5 scale
    confidence = Column(Integer)     # 1-5 how confident in self-assessment
    
    # Additional context
    experience_description = Column(Text)  # User's description of their experience
    goals = Column(Text)  # What they want to achieve
    time_commitment_hours = Column(Float)  # Hours per week available
    
    # AI analysis
    ai_assessed_level = Column(Integer)  # AI's assessment after watching history analysis
    ai_recommendations = Column(JSONB)  # AI suggestions
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    user = relationship("User", back_populates="skill_assessments")
    category = relationship("Category")
    
    def __repr__(self):
        return f"<SkillAssessment {self.skill_name}: {self.current_level} -> {self.target_level}>"
